proxy: "http://mihomo:7890"

user_system:
  db_type: "postgres"
  db_url: "postgresql://user:password@postgres:5432/toolbox?sslmode=disable"
  cloudflare_secret: ""
  smtp:
    smtp_addr: ""
    smtp_port: 25
    smtp_mail: ""
    smtp_pass: ""
    mail_name: ""
  session_sign_token: ""
  avatar_save_dir: "avatars"
  frontend_url: ""
  social_platform_verify_token: ""

mongodb:
  url: "mongodb://user:pass@mongo"
  db: "collections"
  suite: "suite"
  mysekai: "mysekai"
  webhook: "webhook"
  webhook_user: "webhook_user"
  private_api_secret: "Bearer "
  private_api_user_agent: ""

redis:
  host: "localhost"
  port: 6379
  password: ""   # 为空表示无密码

webhook:
  jwt_secret: ""

oauth2:
  auth_code_ttl: 300
  access_token_ttl: 3600
  refresh_token_ttl: 2592000
  token_sign_key: ""

backend:
  host: "0.0.0.0"
  port: 6666
  ssl: false
  ssl_cert: "fullchain.cer"
  ssl_key: "com.key"
  log_level: "INFO"
  main_log_file: "main.log"
  access_log: "[${time}] ${status} - ${latency} ${method} ${path}\n"
  access_log_path: "access.log"
  allow_cors:
    - ""
  enable_trust_proxy: true
  trusted_proxies:
    - "127.0.0.0/8"
    - "::1/128"
    - "192.168.0.0/16"
    - "172.16.0.0/12"
    - "100.64.0.0/10"
    - "10.0.0.0/8"
  proxy_header: "X-Forwarded-For"

third_party_data_provider:
  endpoint_8823: ""
  secret_8823: ""
  endpoint_sakura: ""
  secret_sakura: ""
  endpoint_resona: ""
  secret_resona: ""
  endpoint_luna: ""
  secret_luna: ""

sekai_api:
  api_endpoint: ""
  api_token: ""

haruki_proxy:
  user_agent: "HarukiProxy"
  version: "v1.7.0"
  secret: ""
  unpack_key: ""

sekai_client:
  en_server_api_host: ""
  en_server_aes_key: ""
  en_server_aes_iv: ""
  jp_server_api_host: ""
  tw_server_api_host: ""
  kr_server_api_host: ""
  cn_server_api_host: ""
  other_server_aes_key: ""
  other_server_aes_iv: ""
  jp_server_inherit_token: ""
  en_server_inherit_token: ""
  jp_server_app_version_url: ""
  en_server_app_version_url: ""
  jp_server_inherit_client_headers:
    Host: ""
  en_server_inherit_client_headers:
    Host: ""
  suite_remove_keys:
    - "userInherit"
    - "userMaterials"
    - "userActionSets"
    - "userInformations"
    - "userProfileHonors"
    - "userCustomProfiles"
    - "userEventExchanges"
    - "userMissionStatuses"
    - "userBillingShopItems"
    - "userReleaseConditions"
    - "userCostume3dStatuses"
    - "userCostume3dShopItems"
    - "userCustomProfileCards"
    - "userUnitEpisodeStatuses"
    - "userCustomProfileGachas"
    - "userEventEpisodeStatuses"
    - "userSpecialEpisodeStatuses"
    - "userCustomProfileResources"
    - "userArchiveEventEpisodeStatuses"
    - "userCustomProfileResourceUsages"
    - "userCharacterProfileEpisodeStatuses"


others:
  public_api_allowed_keys:
    - "userDecks"
    - "userCards"
    - "userAreas"
    - "userHonors"
    - "userMusics"
    - "userEvents"
    - "upload_time"
    - "userProfile"
    - "userCharacters"
    - "userWorldBlooms"
    - "userBondsHonors"
    - "userMusicResults"
    - "userMysekaiGates"
    - "userProfileHonors"
    - "userMysekaiCanvases"
    - "userRankMatchSeasons"
    - "userMysekaiMaterials"
    - "userMusicAchievements"
    - "userMysekaiCharacterTalks"
    - "userWorldBloomSupportDecks"
    - "userChallengeLiveSoloDecks"
    - "userChallengeLiveSoloStages"
    - "userChallengeLiveSoloResults"
    - "userChallengeLiveSoloHighScoreRewards"
    - "userMysekaiFixtureGameCharacterPerformanceBonuses"
